### ISSUE TITLE
Issue#1 - Clase Fraction: división de dos fracciones

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#1]
Se pide incluir el método `dividir` que permita la división de dos fracciones. Se le pasará por parámetro la fracción por la cual se quiere dividir la primera. 

Un ejemplo de esta operación podría ser el siguiente:

![image](https://user-images.githubusercontent.com/5214660/30775672-1940d54e-a099-11e7-8851-ea4144c85786.png)

> Tiempo estimado : 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas#dividir-fracciones)

**Comment by GuillermoSanz** [comment]
fixed

**Comment by zuldare** [comment]
Según Sonarcloud hay alguna cosa que debería cambiarse.
En la clase _Fraction_  en el método _dividir_ está devolviendo un aviso de 'smell code'. 
Esto se produce porque estás calculando resultado, guardandolo y posteriormente devolviendo ese resultado. 
Sonar pide que se haga en una instrucción.
El cambio sería esto 
> Fraction franctionResult = new Fraction(this.numerator * fractionB.denominator, this.denominator * fractionB.numerator)
return franctionResult;

cambiarlo por 
> return new Fraction(this.numerator * fractionB.denominator, this.denominator * fractionB.numerator)

Reabro incidencia.

**Comment by GuillermoSanz** [comment]
smell code solved
