### ISSUE TITLE
Issue#2 - Clase Fraction: una fracción es menor que otra

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#2]
Se pide incluir el método `menor`, cuya finalidad es determinar si una fracción es menor a otra fracción pasada por parámetro.

> Tiempo estimado: 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas#calcular-si-una-fracci%C3%B3n-es-menor-a-otra)

**Comment by gmunumel** [comment]
He realizado el cambio. Y he generado un Pull Request.

**Comment by zuldare** [comment]
Ok!

**Comment by zuldare** [comment]
Pasando sonarcloud indica que hay partes del código no cubiertas. En concreto en el método _isMenor_ 
En principio creo que sólo es añadir que haga las comprobaciones
>assertNotNull(fractionB);
>assertNotEquals(0,fractionB.denominator);

Reabro incidencia.

**Comment by gmunumel** [comment]
Agregado cobertura para el issue#2. Subido y merge del Pull Request 👍

**Comment by zuldare** [comment]
¡Todo ok!
