### ISSUE TITLE
Issue#3 - Clase Fraction: comprobar que dos fracciones sean equivalentes

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#3]
Se pide incluir el método ìsEquivalente` . Se le pasará por parámetro la fracción con la que se quiere comprobar la equivalencia.

Dos fracciones son equivalentes cuando el producto de extremos es igual al producto de medios.

![image](https://user-images.githubusercontent.com/5214660/30775942-bd1e4292-a09d-11e7-99bf-57ec3b8f9989.png)

> Tiempo estimado: 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas#ver-si-dos-fracciones-son-equivalentes)

**Comment by asancgom** [comment]
Issue finalizada isEquivalente está creado y probado para la clase Fraction.

**Comment by zuldare** [comment]
Pasando sonarcloud indica que hay partes del código no cubiertas. En concreto en el método _isEquivalente_
En principio creo que sólo es añadir que haga las comprobaciones
>assertNotNull(fractionB);

Reabro incidencia.

**Comment by asancgom** [comment]
Entendido, lo reviso.

**Comment by asancgom** [comment]
Añadida comprobación antes de realizar la operación.

**Comment by zuldare** [comment]
¡Todo ok!
