### ISSUE TITLE
Issue#4 - Clase User: escribir nombre de manera anglosajona

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#4]
Se pide incluir el método `fullNameAnglosaxon()`.
Este método devolverá el nombre y apellido de un usuario  indicando primero el apellido y luego su nombre.

> Tiempo estimado: 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas#nombre-a-la-manera-anglosajona)

**Comment by GuillermoSanz** [comment]
fixed

**Comment by zuldare** [comment]
¡Todo ok!
