### ISSUE TITLE
Issue#5 - Clase DecimalCollection: devolver la media

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#5]
Se pide incluir el método `media`que se encargará de devolver el valor  de la media aritmética de una colección.

Para calcular la media aritmética de una colección bastaría con sumar todos sus elementos y dividir por el tamaño de la colección.

> Tiempo estimado: 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas#calcular-la-media)

**Comment by asancgom** [comment]
Issue finalizado añadiendo la función media a la clase DecimalCollection y su test a la correspondiente clase test.

**Comment by zuldare** [comment]
¡Todo ok, gracias!
