### ISSUE TITLE
Issue#6 - Clase Point: mover un punto a otras cordenadas

### ISSUE THREAD

**Issue by zuldare** [zuldare/IWVG.SwC.JaimeHernandez#6]
Se pide incluir el método `move` que recibirá como parámetro dos valores, la posición en el eje X y la posición en el eje Y a la que se quiere mover el punto.

> Tiempo estimado: 1 día

Para más información [Ver wiki](../wiki/Mejoras-propuestas/_edit#mover-un-punto)

**Comment by gmunumel** [comment]
Finalizado con este issue. Creado Pull request.

**Comment by zuldare** [comment]
Ok!
